object Versions {
    const val gradlePlugin = "4.2.1"
    const val coreKtx = "1.7.0"
    const val appCompat = "1.6.0"
    const val material = "1.8.0"
    const val constraint = "2.1.4"
    const val junit = "4.13.2"
    const val junitTesting = "1.1.5"
    const val espresso = "3.5.1"
    const val hilt = "2.44"
    const val retrofit = "2.9.0"
    const val retrofitGson = "2.9.0"
    const val gson = "2.8.6"
    const val okHttp = "4.9.1"
    const val paging = "3.1.0-alpha03"
    const val daggerHilt = "2.44"
    const val activity = "1.6.0"
    const val fragment = "1.5.3"
    const val glide = "4.14.2"
    const val glideCompiler = "4.14.2"
}